################################################
# Template for bioabakery snakemake workflows. #
################################################

#-------------------
# workflow variables
#-------------------
---
input_folder: "rawfastq"
output_folder: "output"
reads: paired # change to "single" if appropriate
run: all # or: "kneaddata" "metaphlan" "humann"
samples: setup/echo_samples.snakefile

#----------------------
# Environment variables
#----------------------

# # by default, assume these are in $PATH
# # These are not yet used
# executables:
#     kneaddata: kneaddata
#     metaphlan: metaphlan
#     humann: humann
#     diamond: diamond

# these are the paths on your cluster
databases:
    human_sequences: /pool001/vklepacc/databases/Homo_sapiens_bowtie
    chocophlan: /pool001/vklepacc/humann_databases_v3/chocophlan
    # Set with humann_config --> # uniref: /pool001/vklepacc/humann_databases_v3/uniref/
